---
apiVersion: v1
kind: Pod
metadata:
  name: multus1
  annotations:
    k8s.v1.cni.cncf.io/networks: kube-system/macvlan-conf
spec:
  containers:
  - name: iperf
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: jhoblitt/iperf
