---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: comcam-dds
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "br3075",
      "mode": "bridge",
      "ipam": {
        "type": "dhcp"
      }
    }'
