---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo1-pvc
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  selector:
    matchLabels:
      app: demo1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - image: alpine
        name: alpine
        command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
        volumeMounts:
        - name: demo1-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: demo1-persistent-storage
        persistentVolumeClaim:
          claimName: demo1-pvc
